"""Added job metadata

Revision ID: fdba002dd748
Revises: 4578b3944533
Create Date: 2020-06-11 18:54:12.498860

"""
from alembic import op
import sqlalchemy as sa
import airflow

# revision identifiers, used by Alembic.
revision = 'fdba002dd748'
down_revision = '4578b3944533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ergo_job', sa.Column('error_msg', sa.Text(), nullable=True))
    op.add_column('ergo_job', sa.Column('result_code', sa.Integer(), nullable=False))
    op.add_column('ergo_job', sa.Column('result_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ergo_job', 'result_data')
    op.drop_column('ergo_job', 'result_code')
    op.drop_column('ergo_job', 'error_msg')
    # ### end Alembic commands ###
